# Generated by Django 5.1.1 on 2024-09-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0007_alter_enquetes_opcao1_alter_enquetes_opcao2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatar',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
