# Generated by Django 5.1.1 on 2024-09-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatar_problemas',
            old_name='imagem',
            new_name='foto',
        ),
    ]
