# Generated by Django 5.1.1 on 2024-09-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0002_rename_imagem_relatar_problemas_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('problema', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=50)),
                ('foto', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='relatar_problemas',
        ),
    ]
