# Generated by Django 5.1.1 on 2024-09-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0003_relatar_delete_relatar_problemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=3)),
                ('endereco', models.CharField(max_length=300)),
                ('mensagem', models.TextField(max_length=1000)),
                ('opcao1', models.CharField(max_length=50)),
                ('opcao2', models.CharField(max_length=50)),
                ('opcao3', models.CharField(max_length=50)),
                ('sugestao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
