# Generated by Django 5.1.1 on 2024-09-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0004_enquetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquetes',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='enquetes',
            name='idade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='enquetes',
            name='mensagem',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enquetes',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquetes',
            name='opcao1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquetes',
            name='opcao2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquetes',
            name='opcao3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
