# Generated by Django 5.1.1 on 2024-09-26 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0005_alter_enquetes_endereco_alter_enquetes_idade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquetes',
            name='sugestao',
        ),
    ]
