# Generated by Django 5.1.1 on 2024-09-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0006_remove_enquetes_sugestao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquetes',
            name='opcao1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquetes',
            name='opcao2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquetes',
            name='opcao3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
