# Generated by Django 5.1.1 on 2024-09-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0008_alter_relatar_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatar',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
