# Generated by Django 5.1.1 on 2024-10-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0011_alter_enquetes_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('validacao', models.CharField(max_length=50)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
    ]
