# Generated by Django 5.1.1 on 2024-10-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0012_relatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('servico', models.CharField(max_length=255)),
                ('violacao', models.CharField(max_length=255)),
            ],
        ),
    ]
