# Generated by Django 5.1.1 on 2024-10-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0013_alertaseguranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=300)),
                ('servico', models.CharField(max_length=255)),
                ('violacao', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AlertaSeguranca',
        ),
    ]
