# Generated by Django 5.1.1 on 2024-11-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0014_violacao_delete_alertaseguranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_vaga', models.CharField(max_length=255)),
                ('descricao_vaga', models.TextField()),
                ('pretensao_salarial', models.CharField(max_length=100)),
                ('tempo_vaga', models.CharField(choices=[('1-mes', '1 Mês'), ('2-meses', '2 Meses'), ('3-meses', '3 Meses'), ('indeterminado', 'Indeterminado')], max_length=50)),
                ('nivel_escolaridade', models.CharField(choices=[('ensino-fundamental', 'Ensino Fundamental'), ('ensino-medio', 'Ensino Médio'), ('ensino-superior', 'Ensino Superior'), ('pos-graduacao', 'Pós-Graduação'), ('doutorado', 'Doutorado')], max_length=100)),
                ('email_contato', models.EmailField(max_length=254)),
            ],
        ),
    ]
