# Generated by Django 5.1.1 on 2024-11-07 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0015_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoReforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_andamento', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='Aplicacao.relatorio')),
            ],
        ),
    ]
