# Generated by Django 5.1.1 on 2024-11-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0016_avaliacaoreforma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaoreforma',
            old_name='justificativa',
            new_name='comentarios',
        ),
        migrations.RemoveField(
            model_name='avaliacaoreforma',
            name='nota_andamento',
        ),
        migrations.AddField(
            model_name='avaliacaoreforma',
            name='nota',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
    ]
