# Generated by Django 5.1.1 on 2024-11-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacao', '0017_rename_justificativa_avaliacaoreforma_comentarios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaoreforma',
            old_name='comentarios',
            new_name='justificativa',
        ),
        migrations.RemoveField(
            model_name='avaliacaoreforma',
            name='nota',
        ),
        migrations.AddField(
            model_name='avaliacaoreforma',
            name='nota_andamento',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True),
        ),
    ]
